-- WC3 Coach — schema pointer
--
-- packages/db/src/schema.ts is the SINGLE SOURCE OF TRUTH for the DB schema.
-- This file is no longer the canonical definition.
--
-- Schema changes:
--   1. Edit packages/db/src/schema.ts (Drizzle ORM table definitions).
--   2. Generate a new migration:
--        corepack pnpm --filter @wc3-coach/db db:generate
--      This produces a new SQL file in db/migrations/ (e.g. 0002_*.sql).
--   3. Apply to the local DB:
--        corepack pnpm --filter @wc3-coach/db db:migrate
--
-- NEVER alter the live DB by hand — always go through migrations.
-- See docs/WC3_Coach_Design_Doc.md §5 for the data model design.
